import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#f0e8db",
        "tertiary-container": "#c4a66a",
        "tertiary-fixed-dim": "#dcc48e",
        "on-error-container": "#690005",
        "on-primary-fixed": "#002110",
        tertiary: "#705c30",
        "on-secondary-container": "#5e5548",
        "surface-container-high": "#eae6de",
        "error-container": "#ffdad8",
        "surface-container-low": "#f5f1ea",
        "on-surface": "#2e3230",
        error: "#b83230",
        "surface-tint": "#4a7c59",
        "surface-bright": "#faf6f0",
        "surface-container-highest": "#e4e0d8",
        "on-tertiary-fixed": "#221a05",
        "surface-variant": "#e4e0d8",
        surface: "#faf6f0",
        "inverse-on-surface": "#f5f0e8",
        "inverse-surface": "#2e3230",
        "primary-fixed-dim": "#8ecf9e",
        "inverse-primary": "#8ecf9e",
        "on-primary-container": "#d8f0de",
        "outline-variant": "#c4c8bc",
        "on-secondary-fixed-variant": "#4a4538",
        "surface-dim": "#dbd7cf",
        "on-surface-variant": "#4a4e4a",
        "on-primary-fixed-variant": "#2a6038",
        "on-secondary-fixed": "#1e1a13",
        "tertiary-fixed": "#f8e0a8",
        background: "#faf6f0",
        "surface-container": "#f0ece4",
        "on-error": "#ffffff",
        "secondary-fixed": "#f0e8db",
        "on-tertiary-container": "#554020",
        "secondary-fixed-dim": "#d4ccbf",
        primary: "#4a7c59",
        secondary: "#6b6358",
        "primary-container": "#78a886",
        "on-tertiary-fixed-variant": "#554020",
        "on-secondary": "#ffffff",
        "on-background": "#2e3230",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        outline: "#74796e",
        "primary-fixed": "#c8e8d0",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        lg: "24px",
        base: "4px",
        "editor-width": "800px",
        sm: "8px",
        xl: "48px",
        "container-max": "1200px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Manrope"],
        "body-lg": ["Inter"],
        "headline-xl": ["Manrope"],
        "label-caps": ["Inter"],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
        headline: ["Literata"],
        display: ["Literata"],
        body: ["Nunito Sans"],
        label: ["Nunito Sans"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        mono: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

export default config;
